export const RECEIVE_ADDRESS = 'receive_adress'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_CATEGORYS  = 'receive_categorys'
export const RECEIVE_CAPTCHE = 'receive_captche'
export const RECEIVE_USER_INFO = 'receive_user_info'   // 接收用户信息
export const RESET_USER_INFO = 'reset_user_info'   // 重置用户信息
export const RECEIVE_GOODS = 'receive_goods' // 接收商品数组
export const RECEIVE_RATINGS = 'receive_ratings' // 接收商家评价数组
export const RECEIVE_INFO = 'receive_info' // 接收商家信息
export const INCREASE = 'increase'  
export const DECREASE = 'decrease'  